name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome message, List Files, Read the Readme file
              run: |
                echo "My first GitHub Actions job"
                ls -ltra
                cat README.md
                
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Hello DevOps, I'm going to you! You'll see me soon!" > dragon.txt
            # - name: List Files
            #   run: ls

            # - name: Read the Readme file
            #   run: cat README.md