name: Exploring Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker login
              env:
                DOCKER_PASSWORD: s3cUrePaSsw0rd
              run: echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest